.\" Copyright (c) 2001 Kipp Cannon (kcannon@users.sourceforge.net)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH bkrencode 8 "March 21, 2001" "Linux" "Backer"
.SH NAME
bkrencode \- Backer tape data processor.
.SH SYNOPSIS
\fBbkrencode\fP [-h] [-u] [-V n|p] [-D h|l] [-F e|s] [-a] [-f
\fIdevname\fP]
.SH DESCRIPTION
\fBbkrencode\fP is a user space implementation of the
.IR backer (4)
device driver's data processing functions.  It is a filter that reads data
from standard in and writes it to standard out.  It can either accept file
data and encode it into a byte stream suitable for being written directly
to tape or accept a raw byte stream recovered from tape and decode the file
data out of it.  The default is to encode file data to tape data.
.PP
There are two uses for \fBbkrencode\fP.  On the one hand it allows the tape
data stream to be processed ``off line''.  This is useful for systems which
are not fast enough to process the tape data in real time.  Tape data can
be prepared on disk ahead of time with \fBbkrencode\fP and then dumped to
tape via a raw device (and vice versa when reading tapes).  This, of
course, requires enough free disk space to be available to act as a buffer.
The other use of \fBbkrencode\fP is to allow tapes recorded with older
versions of the device driver to be recovered when the current version of
the driver cannot read the older format.  All that is required is a version
of \fBbkrencode\fP compiled from the sources of the older driver.
.PP
It is necessary to tell \fBbkrencode\fP what format to use when encoding a
tape data stream and, likewise, the format the data stream is in when it's
being decoded.  If the mode is not specified on the command line then the
compiled-in default mode is used.  It is possible for \fBbkrencode\fP to
automatically retrieve the format to use from a device file.  This is done
with the \fI-a\fP option combined with the \fI-f\fP option if necessary and
can be done whether or not the device is actually in use for a transfer at
the time.
.SS OPTIONS
.TP
\-h
Print a usage message.
.TP
\-u
Unencode.  Extract file data from tape data stream.
.TP
\-V [np]
Set the video mode to format the data for to NTSC (n) or PAL (p).
.TP
\-D [hl]
Set the density to format the data for to high (h) or low (l).
.TP
\-F [es]
Set the tape speed to format the data for to EP (e) or SP (s).
.TP
\-a
Automatically retrieve the mode to use from a Backer device file.
.TP
\-f \fIdevname\fP
When automatically retrieving the desired mode, retrieve it from
\fIdevname\fP.  If this option is not given then the mode is retrieved from
the compiled-in default file.
.SH EXAMPLES
The following examples assume that the device file system is in use.  If
not, adjust the device names appropriately.  To save a file to tape with a
short play high density NTSC recording using \fBbkrencode\fP to process the
data type
.RS
.sp
bkrencode -V n -D h -S s < \fIfilename\fP > /dev/backer/0/nhr
.sp
.RE
and to retrieve it type
.RS
.sp
bkrencode -u -V n -D h -S s < /dev/backer/0/nhr > \fIfilename\fP
.sp
.RE
To use \fBbkrencode\fP to allow
.IR tar (1)
to be used with high compression on a slow computer do something like
.RS
.sp
tar -czO \fIfilenames...\fP | bkrencode > /tmp/tape.dat
.br
cat /tmp/tape.dat > /dev/backer/0/\fIdevice\fP
.sp
.RE
.SH NOTES
It is essential that \fBbkrencode\fP be set to a format appropriate for the
mode used to transfer the data to/from tape.  If, for example,
\fBbkrencode\fP is told to produce a PAL compatible data stream which is
then written to tape via an NTSC device file the resulting recording will
be irrecoverable.
.SH "SEE ALSO"
.IR backer (4),
.IR bkrcheck (8),
.IR bkrmonitor (8)
.SH AUTHOR
Kipp Cannon (kcannon@users.sourceforge.net).
.SH AVAILABILITY
The most recent version of the driver and utilities can be found on
SourceForge at:
.RS
.sp
http://www.sourceforge.net/projects/linbacker
.sp
.RE
.TE
