#!/bin/bash

#
# enum values taken from backer.h
#

BKR_NTSC=1
BKR_PAL=2
BKR_LOW=4
BKR_HIGH=8


#
# defaults
#

DEFAULT_VIDEOMODE=${BKR_NTSC}
DEFAULT_BITDENSITY=${BKR_HIGH}


#
# parse command line
#

function usage() {
	echo "Usage: bkrvideo [-V{n|p}] [-D{h|l}] < input"
}

VIDEOMODE=${DEFAULT_VIDEOMODE}
BITDENSITY=${DEFAULT_BITDENSITY}

while getopts "V:D:" OPT ; do
	case "${OPT}" in
	V)
		case "${OPTARG}" in
		n)
			VIDEOMODE=${BKR_NTSC} ;;
		p)
			VIDEOMODE=${BKR_PAL} ;;
		*)
			usage
			exit 1 ;;
		esac ;;
	D)
		case "${OPTARG}" in
		l)
			BITDENSITY=${BKR_LOW} ;;
		h)
			BITDENSITY=${BKR_HIGH} ;;
		*)
			usage
			exit 1 ;;
		esac ;;
	*)
		usage
		exit 1 ;;
	esac
done


#
# construct and run pipeline
#

gst-launch-0.8 fdsrc ! bkr_video_out videomode=${VIDEOMODE} bitdensity=${BITDENSITY} ! ximagesink
