#!/bin/bash

#
# enum values taken from backer.h
#

BKR_NTSC=1
BKR_PAL=2
BKR_LOW=4
BKR_HIGH=8


#
# defaults
#

DEFAULT_VIDEOMODE=${BKR_NTSC}
DEFAULT_BITDENSITY=${BKR_HIGH}


#
# parse command line
#

function usage() {
	echo "Usage: bkrvideo [-Vn|-Vp] [-Dh|-Dl] [-v] < input"
}

VIDEOMODE=${DEFAULT_VIDEOMODE}
BITDENSITY=${DEFAULT_BITDENSITY}
VERBOSE=""

while getopts "D:V:v" OPT ; do
	case "${OPT}" in
	D)
		case "${OPTARG}" in
		l)
			BITDENSITY=${BKR_LOW} ;;
		h)
			BITDENSITY=${BKR_HIGH} ;;
		*)
			usage
			exit 1 ;;
		esac ;;
	V)
		case "${OPTARG}" in
		n)
			VIDEOMODE=${BKR_NTSC} ;;
		p)
			VIDEOMODE=${BKR_PAL} ;;
		*)
			usage
			exit 1 ;;
		esac ;;
	v)
		VERBOSE="-v" ;;
	*)
		usage
		exit 1 ;;
	esac
done


#
# construct and run pipeline
#

PIPELINE="fdsrc fd=0 ! bkr_video_out videomode=${VIDEOMODE} bitdensity=${BITDENSITY} ! ximagesink"

if [ "${VERBOSE}" == "-v" ] ; then
	echo "Pipeline:  ${PIPELINE}"
fi

#DEBUGFLAGS="--gst-debug-level=4"

gst-launch ${DEBUGFLAGS} ${VERBOSE} ${PIPELINE}
