.\" Copyright (c) 2001 Kipp Cannon (kcannon@users.sourceforge.net)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH BACKER_ISA 4 "August 15, 2001" "Linux" "Special Files"
.SH NAME
backer_isa \- ISA Backer device support.
.SH INTRODUCTION
This is a hardware interface module for the
.IR backer (4)
device driver providing access to ISA Backer devices.
.SH CONFIGURATION
When loaded, this module will autoprobe for the presence of ISA Backer
devices.  Devices will be registered in the numerical order of their I/O
ports.  If autoprobing fails for some reason then it can be disabled and
all interface cards' resources specified manually via a module option.
.SS OPTIONS
This module accepts the following option.
.TP
\fBisa=\fIioport,dma[,ioport,dma,...]\fP
Specify the I/O port and DMA channel used by each ISA card, one pair of
numbers per card.  A maximum of three devices can be specified in this way.
All autoprobing is disabled when this option is provided.
.PP
Early versions of the card could only use DMA channel 1.  Later versions
could be jumpered to channel 1 or 3 and were shipped with a factory default
of 3.  The factory default I/O port was 0x300.
.PP
ISA Backer cards can share a DMA channel but then only one of them can be used
at a time.  It is not possible for ISA cards to share an I/O port and the
driver will discard duplicate entries.
.SH ERRORS
The following is a list of the error codes that can be generated by this
module and the reasons for them.
.IP \fBENODEV\fP
.PD 0
.RS +0.5i
.TP 2
o
No devices could be found at module load time.
.RE
.PD 1
.SH "SEE ALSO"
.IR backer (4),
.IR backer_parport (4)
.SH AUTHOR
Kipp Cannon (kcannon@users.sourceforge.net).
.SH AVAILABILITY
The most recent version of the driver and utilities can be found on
SourceForge at:
.RS
.sp
http://www.sourceforge.net/projects/linbacker
.sp
.RE
.TE
