.\" Copyright (c) 2001 Kipp Cannon (kcannon@users.sourceforge.net)
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.TH BACKER_PARPORT 4 "December 30, 2001" "Linux" "Special Files"
.SH NAME
backer_parport \- Parallel port Backer device support.
.SH INTRODUCTION
This is a hardware interface module for the
.IR backer (4)
device driver providing access to external Backer devices.
.SH CONFIGURATION
This module does not have autoprobe capabilities so it must be told the
names of the parallel ports to which Backer devices are attached.  Devices
will be registered in the order in which the Linux parport driver informs
this driver of the specified ports.  This should be in numerical order by
port number.  For example, the Backer device attached to parport0 will be
registered before the device attached to parport1.
.PP
This module will remain loaded regardless of whether or not it succeeds in
finding the specified port(s).  This is done to support the possibility
that the ports are hot-pluggable devices (eg. part of a laptop docking
station) and might become available at a later time.
.SS OPTIONS
This module accepts the following options.  The \fBunits=\fP option is
required.
.TP
\fBunits=\fP\fIparport\fP[:\fIparport\fP:...]
Specify the names of the parallel ports to which Backer devices are
attached, for example ``parport0''.  Any number of ports can be specified
and the driver will register one Backer device for each as they become
available.
.TP
\fBadjust=\fP\fImicroseconds\fP
Specify an adjustment to the default start-up delay in microseconds.
.PP
Due to limitations in the external Backer's design, only one can be
attached to each parallel port.  If multiple devices are attached to the
same port, then they cannot be controled independantly.
.SH BUGS
Due to weaknesses in the design of Linux's parport architecture, it is not
possible to use it to support the external Backer device.  Instead, it is
necessary for this driver to access the parallel port hardware directly in
order to accomplish the I/O.  This has the consequence that this driver can
only be used with x86 architectures and probably on a narrower range of
systems than the actual parport_pc driver.  Certainly this driver will not
work with as wide a range of parallel port hardware as it is, in principle,
possible to use the Backer device with.
.PP
Unfortunately, this situation will not change unless a rather significant
re-write of the Linux paport subsystem is undertaken.
.SH ERRORS
The following is a list of the error codes that can be generated by this
module and the reasons for them.
.IP \fBEBUSY\fP
.PD 0
.RS +0.5i
.TP 2
o
The parallel port is in use and cannot be claimed.
.RE
.PD 1
.IP \fBENODEV\fP
.PD 0
.RS +0.5i
.TP 2
o
No parallel ports were specified at module load time.
.RE
.RS +0.5i
.TP 2
o
The driver could not register itself with the parport subsystem.
.RE
.PD 1
.IP \fBENOMEM\fP
.PD 0
.RS +0.5i
.TP 2
o
A unit's I/O buffer could not be allocated on read/write.
.RE
.PD 1
.SH "SEE ALSO"
.IR backer (4),
.IR backer_isa (4)
.SH AUTHOR
Kipp Cannon (kcannon@users.sourceforge.net).
.SH AVAILABILITY
The most recent version of the driver and utilities can be found on
SourceForge at:
.RS
.sp
http://www.sourceforge.net/projects/linbacker
.sp
.RE
.TE
